"""Markdown report generator from debate state."""

from __future__ import annotations

from datetime import datetime
from typing import List

from think_tank.schemas import DebateState, DebateSpec, Panel, Move


def generate_report(
    state: DebateState,
    spec: DebateSpec,
    panel: Panel,
) -> str:
    """Generate a Markdown report from a completed debate."""

    lines: List[str] = []
    w = lines.append

    w(f"# {state.spec_title}\n")
    w(f"## Think Tank Debate Report\n")
    w(f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    w(f"**Panel**: {state.panel_name} ({state.num_experts} experts)")
    w(f"**Rounds**: {state.num_rounds}")
    w(f"**Total Moves**: {len(state.moves)}")
    w(f"**Total Claims**: {state.total_claims}")
    w(f"**Model**: {state.model} (synthesis: {state.synth_model})")
    w(f"**Tokens**: {state.total_input_tokens:,} in / {state.total_output_tokens:,} out\n")

    # Expert panel table
    w("## Expert Panel\n")
    w("| # | Expert | Role | Domain |")
    w("|---|--------|------|--------|")
    for i, expert in enumerate(panel.experts, 1):
        domain = expert.domain or "-"
        w(f"| {i} | {expert.name} | {expert.title} | {domain} |")
    w("")
    w("---\n")

    # Per-round sections
    for rnd in spec.rounds:
        w(f"# Round {rnd.number}: {rnd.focus}\n")
        w(f"**Question**: {rnd.question}\n")

        round_moves = [m for m in state.moves if m.round == rnd.number]

        for move in round_moves:
            _write_move(w, move)

        w("---\n")

    # Claim index
    all_claims = []
    for move in state.moves:
        for claim in move.claims:
            all_claims.append((move, claim))

    if all_claims:
        w("# Claim Index\n")
        w("| ID | Confidence | Stance | Agent | Claim |")
        w("|----|-----------|--------|-------|-------|")
        for move, claim in all_claims:
            stance_marker = {"pro": "+", "contra": "-", "neutral": "~"}.get(
                claim.stance, "?"
            )
            short_text = claim.text[:100] + ("..." if len(claim.text) > 100 else "")
            w(
                f"| {claim.id} | {claim.confidence:.2f} | "
                f"{stance_marker} | {move.agent_id} | {short_text} |"
            )
        w("")

    # Consensus analysis
    if all_claims:
        w("# Consensus Analysis\n")
        _write_consensus(w, all_claims)

    w("\n---\n")
    w(f"*Generated by Think Tank v0.1.0 on {datetime.now().isoformat()}*\n")

    return "\n".join(lines)


def _write_move(w, move: Move):
    """Write a single move section."""
    w(f"## {move.agent_title}\n")

    if move.move_type == "error":
        w(f"> **ERROR**: {move.content}\n")
        return

    w(f"{move.content}\n")

    if move.claims:
        w("### Key Claims\n")
        for c in move.claims:
            conf = c.confidence
            stance = c.stance
            marker = {"pro": "+", "contra": "-", "neutral": "~"}.get(stance, "?")
            w(f"- [{marker}] **{c.id}** [{conf:.2f}]: {c.text}")
            for ev in c.evidence:
                w(f"  - *{ev.source}*: {ev.quote[:200]}")
            for asmp in c.assumptions:
                w(f"  - Assumption: {asmp}")
        w("")

    if move.targets:
        w(f"*Challenges*: {', '.join(move.targets)}\n")


def _write_consensus(w, all_claims):
    """Analyze and write consensus/dissensus summary."""
    # Group by stance
    pro = [c for _, c in all_claims if c.stance == "pro"]
    contra = [c for _, c in all_claims if c.stance == "contra"]
    neutral = [c for _, c in all_claims if c.stance == "neutral"]

    w(f"- **Pro claims**: {len(pro)}")
    w(f"- **Contra claims**: {len(contra)}")
    w(f"- **Neutral claims**: {len(neutral)}")
    w("")

    # High-confidence claims (>= 0.85)
    high_conf = [(m, c) for m, c in all_claims if c.confidence >= 0.85]
    if high_conf:
        w("### High-Confidence Claims (>= 0.85)\n")
        for move, claim in high_conf:
            w(f"- **{claim.id}** [{claim.confidence:.2f}] ({move.agent_id}): {claim.text[:150]}")
        w("")

    # Low-confidence claims (<= 0.4) — areas of uncertainty
    low_conf = [(m, c) for m, c in all_claims if c.confidence <= 0.4]
    if low_conf:
        w("### Areas of Uncertainty (<= 0.4 confidence)\n")
        for move, claim in low_conf:
            w(f"- **{claim.id}** [{claim.confidence:.2f}] ({move.agent_id}): {claim.text[:150]}")
        w("")
